SET LINESIZE 200
SET PAGESIZE 100
COLUMN Name FORMAT A20
COLUMN Email FORMAT A10
COLUMN Student_ID FORMAT A8
COLUMN College_ID FORMAT A8
COLUMN Acad_Status FORMAT A10
COLUMN Phone FORMAT A12
COLUMN Majro FORMAT A20

SELECT * FROM Fall25_S0003_T1_Student;