SET LINESIZE 200
SET PAGESIZE 100
COLUMN License_ID FORMAT A10
COLUMN Provider_ID FORMAT A10
COLUMN License_Type FORMAT A16
COLUMN License_Cost FORMAT A16
COLUMN Start_Date FORMAT A10
COLUMN End_Date FORMAT A10
COLUMN Renew_Terms FORMAT A16

SELECT * FROM Fall25_S0003_T1_License;